version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: "vu"
          command: |
            echo ${CIRCLE_BRANCH}
workflows:
  test-env-vars:
    jobs:
      - build